apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: dev-verified-promote-to-staging
spec:
  params:
    - name: gitUrl
      type: string
      description: GitOps repository URL

    - name: appName
      type: string
      description: Application folder under apps/

    - name: gitRevision
      type: string
      default: main
      description: Git branch to update

  workspaces:
    - name: doc-source

  tasks:
    - name: promote-dev-to-staging
      taskRef:
        name: promote-dev-to-staging
      params:
        - name: gitUrl
          value: $(params.gitUrl)
        - name: appName
          value: $(params.appName)
        - name: gitRevision
          value: $(params.gitRevision)
      workspaces:
        - name: doc-source
          workspace: doc-source

