apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: promote-dev-to-staging
spec:
  params:
    - name: gitUrl
      type: string
    - name: gitRevision
      type: string
      default: main
    - name: appName
      type: string

  workspaces:
    - name: doc-source

  steps:
    # ---------------------------
    # 1. Clone GitOps repo
    # ---------------------------
    - name: git-clone
      image: registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8:v1.6.2-21
      workingDir: $(workspaces.doc-source.path)
      script: |
        #!/usr/bin/env sh
        set -e
        git clone -b $(params.gitRevision) "$(params.gitUrl)" repo

    # ---------------------------
    # 2. Promote image (YAML-safe)
    # ---------------------------
    - name: promote-image
      image: mikefarah/yq:4
      workingDir: $(workspaces.doc-source.path)/repo
      script: |
        #!/usr/bin/env sh
        set -e

        DEV_FILE="apps/$(params.appName)/dev/deployment.yaml"
        STAGE_FILE="apps/$(params.appName)/staging/deployment.yaml"

        echo "🔍 Reading image from DEV"
        IMAGE=$(yq '.spec.template.spec.containers[0].image' "$DEV_FILE")

        if [ -z "$IMAGE" ] || [ "$IMAGE" = "null" ]; then
          echo "ERROR: Could not read image from DEV deployment"
          exit 1
        fi

        echo "✅ Promoting image: $IMAGE"

        yq -i '.spec.template.spec.containers[0].image = strenv(IMAGE)' "$STAGE_FILE"

    # ---------------------------
    # 3. Commit & push
    # ---------------------------
    - name: git-push
      image: registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8:v1.6.2-21
      workingDir: $(workspaces.doc-source.path)/repo
      script: |
        #!/usr/bin/env sh
        set -e

        git config --global user.email "tekton@tekton.dev"
        git config --global user.name "Tekton Pipeline"

        git add apps/$(params.appName)/staging/deployment.yaml
        git commit -m "Promote $(params.appName) from DEV to STAGING" || true
        git push origin $(params.gitRevision)

